# Generated by Django 4.0.10 on 2024-06-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_location_latitude_remove_location_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='country_code',
        ),
        migrations.AddField(
            model_name='location',
            name='region',
            field=models.CharField(default='empty', max_length=255),
            preserve_default=False,
        ),
    ]
