# Generated by Django 4.0.10 on 2024-07-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_location_country_code_location_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='country',
        ),
        migrations.RemoveField(
            model_name='location',
            name='region',
        ),
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
