# Generated by Django 4.0.10 on 2024-07-02 17:10

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_location_country_remove_location_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.location_image_file_path),
        ),
    ]
